trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the main branch

variables:
  - group: SECRET_KEY  # Reference your variable group containing MONGO_URI and other secrets
  - name: ACR_NAME
    value: wumiibo
  - name: FRONTEND_IMAGE
    value: is402-frontend
  - name: BACKEND_IMAGE
    value: is402-backend
  - name: APP_NAME_DEV
    value: wumiibo-dev
  - name: APP_NAME_PROD
    value: wumiibo
  - name: RESOURCE_GROUP_DEV
    value: Wumiibo-Dev
  - name: RESOURCE_GROUP_PROD
    value: Wumiibo

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    steps:
    - task: AzureCLI@2
      displayName: Login to Azure Container Registry
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):$(Build.BuildId) -f frontend/Dockerfile .
        docker push $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):$(Build.BuildId)
      displayName: Build and Push Frontend Image

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE):$(Build.BuildId) -f backend/Dockerfile .
        docker push $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE):$(Build.BuildId)
      displayName: Build and Push Backend Image

- stage: DeployDev
  displayName: Deploy to Development Environment
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: DeployDev
    displayName: Deploy Containers to Development
    steps:
    - task: AzureCLI@2
      displayName: Deploy Development Containers
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Login to Azure Container Registry
          az acr login --name $(ACR_NAME)

          # Export the MONGO_URI for development from secrets
          export MONGO_URI=$(MONGO_URI_DEV)

          # Deploy containers using docker-compose.prod.yml for the development environment
          MONGO_URI=$MONGO_URI docker-compose -f docker-compose.prod.yml up --build -d

- stage: DeployProd
  displayName: Deploy to Production Environment
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: DeployProd
    displayName: Deploy Containers to Production
    steps:
    - task: AzureCLI@2
      displayName: Deploy Production Containers
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Login to Azure Container Registry
          az acr login --name $(ACR_NAME)

          # Export the MONGO_URI for production from secrets
          export MONGO_URI=$(MONGO_URI_PROD)

          # Deploy containers using docker-compose.prod.yml for the production environment
          MONGO_URI=$MONGO_URI docker-compose -f docker-compose.prod.yml up --build -d
