trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the 'main' branch

variables:
  - group: SECRET_KEY  # Fetch variables from the Variable Group named "SECRET_KEY"

  - name: FRONTEND_IMAGE
    value: is402-frontend
  - name: BACKEND_IMAGE
    value: is402-backend

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images to ACR
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Images
    pool:
      name: Self-hosted 1  # Use the self-hosted agent pool
    steps:
    - script: |
        echo "Logging in to ACR..."
        echo $(ACR_PASSWORD) | docker login $(ACR_LOGIN_SERVER) -u $(ACR_USERNAME) --password-stdin
      displayName: Log in to ACR

    - script: |
        echo "Building and pushing frontend image..."
        docker build -t $(ACR_LOGIN_SERVER)/$(FRONTEND_IMAGE):latest ./frontend
        docker push $(ACR_LOGIN_SERVER)/$(FRONTEND_IMAGE):latest
      displayName: Build and Push Frontend Image

    - script: |
        echo "Building and pushing backend image..."
        docker build -t $(ACR_LOGIN_SERVER)/$(BACKEND_IMAGE):latest ./backend
        docker push $(ACR_LOGIN_SERVER)/$(BACKEND_IMAGE):latest
      displayName: Build and Push Backend Image

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy Docker Compose to App Service
    pool:
      name: Self-hosted 1
    steps:
    - script: |
        echo "Creating Docker Compose file for production deployment..."
        echo "
        version: '3.8'

        services:
          frontend:
            image: $(ACR_LOGIN_SERVER)/$(FRONTEND_IMAGE):latest
            ports:
              - '3000:3000'
            environment:
              - NODE_OPTIONS=--openssl-legacy-provider
              - CHOKIDAR_USEPOLLING=true

          backend:
            image: $(ACR_LOGIN_SERVER)/$(BACKEND_IMAGE):latest
            ports:
              - '5000:5000'
            env_file: ./backend/.env
            environment:
              - MONGO_URI=${MONGO_URI}

        networks:
          is402:
            driver: bridge
        " > docker-compose.prod.yml
      displayName: Generate Docker Compose File

    - script: |
        echo "Deploying containers to Azure App Service..."
        az webapp config container set \
          --name wumiiboshop \
          --resource-group Wumiibo \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose.prod.yml
      displayName: Deploy to Azure App Service
