trigger:
  - main  # Trigger pipeline on changes to 'main' branch

variables:
  azureSubscription: '974ba5ab-9bc7-41c7-84ac-d53863572299'  # Azure Subscription ID
  webAppName: 'wumiibo'  # Azure Web App Name
  environmentName: 'wumiibo'  # Deployment environment
  serverPort: 8080  # Node.js server port
  nodeVersion: '20.x'  # Node.js version

stages:
- stage: Build
  displayName: "Build MERN Application"
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    pool:
      name: Self-hosted  # Use your self-hosted agent pool
      clean: true  # Clean the workspace before running

    steps:
    # Step 1: Install Node.js 20 LTS (Ensure it's pre-installed on your self-hosted agent)
    - script: |
        node --version
        npm --version
      displayName: 'Verify Node.js and npm Installation'

    # Step 2: Install dependencies and build backend
    - script: |
        cd backend
        npm install
        npm run build --if-present
      displayName: 'Install and Build Backend'

    # Step 3: Install dependencies and build frontend
    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Install and Build Frontend'

    # Step 4: Package the application
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          function Create-ZipFile($zipFile, $sourceFolder) {
            [System.IO.Compression.ZipFile]::CreateFromDirectory($sourceFolder, $zipFile)
          }
          Create-ZipFile "$(Build.ArtifactStagingDirectory)/mern-app.zip" "$(System.DefaultWorkingDirectory)"
      displayName: 'Package the Application'

    # Step 5: Publish the artifact for deployment
    - publish: $(Build.ArtifactStagingDirectory)/mern-app.zip
      artifact: drop
      displayName: 'Publish Build Artifact'

- stage: Deploy
  displayName: "Deploy MERN Application"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: "Deploy Job"
    pool:
      name: Self-hosted  # Use your self-hosted agent pool

    steps:
    # Step 1: Deploy the app to Azure Web App
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: webAppLinux
        appName: $(webAppName)
        runtimeStack: 'NODE|20-lts'
        package: '$(Pipeline.Workspace)/drop/mern-app.zip'
        startUpCommand: 'node backend/server.js --port $(serverPort)'
      displayName: 'Deploy MERN App to Azure'
