trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the 'main' branch

variables:
  group: SECRET_KEY
  # New Azure Container Registry Name
  ACR_NAME: wumiibo-2
  
  # Image names
  FRONTEND_IMAGE: is402-frontend
  BACKEND_IMAGE: is402-backend
  MONGO_IMAGE: mongo
  # Azure Web App and Resource Group
  APP_NAME: wumiibo  # Azure Web App name
  RESOURCE_GROUP: Wumiibo  # Resource group containing Azure Web App

stages:
- stage: SetupACR
  displayName: Create New Azure Container Registry
  jobs:
  - job: CreateACR
    displayName: Create Azure Container Registry
    pool:
      name: Self-hosted 1
    steps:
    - task: AzureCLI@2
      displayName: Create Azure Container Registry
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299  # Service Connection to Azure
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr create `
            --name $(ACR_NAME) `
            --resource-group $(RESOURCE_GROUP) `
            --sku Basic `
            --admin-enabled true

- stage: BuildAndPush
  displayName: Build and Push Docker Images
  dependsOn: SetupACR  # Ensure ACR is created before this stage
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    pool:
      name: Self-hosted 1
    steps:
    - task: AzureCLI@2
      displayName: Login to Azure Container Registry
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):latest -f frontend/Dockerfile .
        docker push $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):latest
      displayName: Build and Push Frontend Image
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE):latest -f backend/Dockerfile .
        docker push $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE):latest
      displayName: Build and Push Backend Image
    - script: |
        docker pull mongo:latest
        docker tag mongo:latest $(ACR_NAME).azurecr.io/$(MONGO_IMAGE):latest
        docker push $(ACR_NAME).azurecr.io/$(MONGO_IMAGE):latest
      displayName: Push MongoDB Image

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush  # Ensure images are pushed before this stage
  jobs:
  - job: Deploy
    displayName: Deploy Containers to Azure Web App
    pool:
      name: Self-hosted 1
    steps:
    - task: AzureCLI@2
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config container set `
            --name $(APP_NAME) `
            --resource-group $(RESOURCE_GROUP) `
            --docker-custom-image-name $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):latest `
            --docker-registry-server-url https://$(ACR_NAME).azurecr.io `
            --docker-registry-server-user $(AZURE_ACR_USERNAME) `
            --docker-registry-server-password $(AZURE_ACR_PASSWORD)
