trigger:
  - main  # Trigger the pipeline on changes to the 'main' branch

variables:
  azureSubscription: '974ba5ab-9bc7-41c9-84ac-d53863572299'
  webAppName: 'wumiibo'
  environmentName: 'wumiibo'
  selfHostedPoolName: 'Self-hosted'
  serverPort: 8080

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build and Test"
    pool:
      name: $(selfHostedPoolName)

    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    # Navigate to backend folder and install dependencies
    - script: |
        cd backend
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'Install dependencies, build, and test'

    # Archive the backend folder
    - task: ArchiveFiles@2
      displayName: 'Archive Build Artifacts'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    # Publish the artifact for the next stage
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
      displayName: 'Publish Build Artifacts'

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: "Deploy to Azure"
    environment: $(environmentName)
    pool:
      name: $(selfHostedPoolName)

    strategy:
      runOnce:
        deploy:
          steps:
          # Deploy the app to Azure Web App
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App: $(webAppName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|20LTS'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              startUpCommand: 'node server.js --port $(serverPort)'  # Ensure server.js is executed
