trigger:
  branches:
    include:
      - main  # Pipeline sẽ chạy khi có thay đổi trên nhánh 'main'

variables:
  # ACR Configuration
  ACR_NAME: wumiibo3  # Tên ACR mới
  RESOURCE_GROUP: Wmiibo  # Nhóm tài nguyên hiện tại
  LOCATION: southeastasia  # Vị trí của ACR
  SKU: Basic  # Gói ACR (Basic, Standard, Premium)

  # App Service
  APP_NAME: wumiibo3  # Tên App Service

stages:
- stage: CreateACR
  displayName: Create Azure Container Registry
  jobs:
  - job: CreateACRJob
    displayName: Create ACR Job
    pool:
      name: 'Self-hosted 1'  # Sử dụng hosted agent
    steps:
    - task: AzureCLI@2
      displayName: Create Azure Container Registry
      inputs:
        azureSubscription: AzureForStudents-Wumiibo-Connection # Tên Service Connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Creating ACR..."
          az acr create \
            --name $(ACR_NAME) \
            --resource-group $(RESOURCE_GROUP) \
            --sku $(SKU) \
            --location $(LOCATION) \
            --admin-enabled true
          echo "ACR created successfully!"

- stage: DeployToAppService
  displayName: Deploy to Azure App Service
  dependsOn: CreateACR  # Đảm bảo ACR được tạo trước khi triển khai
  jobs:
  - job: DeployJob
    displayName: Deploy Application to App Service
    pool:
      name: 'Self-hosted 1'
    steps:
    - task: AzureCLI@2
      displayName: Deploy Application to App Service
      inputs:
        azureSubscription: AzureForStudents-Wumiibo-Connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Deploying App Service..."
          az webapp create \
            --resource-group $(RESOURCE_GROUP) \
            --plan $(APP_NAME)-Plan \
            --name $(APP_NAME) \
            --deployment-container-image-name $(ACR_NAME).azurecr.io/your-image-name:latest
          echo "App Service deployed successfully!"
