trigger:
  - main  # Trigger pipeline on changes to the 'main' branch

variables:
  azureSubscription: '974ba5ab-9bc7-41c9-84ac-d53863572299'  # Azure Subscription
  webAppName: 'wumiibo'  # Azure Web App name
  environmentName: 'wumiibo'  # Deployment environment
  serverPort: 8080  # Port for Node.js server

stages:
# 1. Build Stage
- stage: Build
  displayName: "Build Application"
  jobs:
  - job: BuildBackend
    displayName: "Build and Test Backend"
    pool:
      name: Self-hosted  # Use Self-hosted Agent Pool
      clean: true  # Clean the working directory before the job runs
    steps:
    # Install Node.js 20
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'  # Install Node.js version 20
      displayName: 'Install Node.js 20'

    # Update npm to the latest version
    - script: |
        npm install -g npm@latest
        npm --version
      displayName: 'Update npm to the latest version'

    # Install dependencies and build backend
    - script: |
        cd backend
        npm install
        npm run build --if-present
      displayName: 'Install dependencies and build backend'

    # Archive backend into an artifact
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true
      displayName: 'Archive Backend'

    # Publish artifact
    - publish: $(Build.ArtifactStagingDirectory)/backend.zip
      artifact: drop
      displayName: 'Publish Backend Artifact'

# 2. Deploy Stage
- stage: Deploy
  displayName: "Deploy Application"
  dependsOn: Build
  condition: succeeded()  # Only run if Build stage is successful
  jobs:
  - deployment: DeployToAzure
    displayName: "Deploy Backend to Azure Web App"
    environment: $(environmentName)  # Deployment environment
    pool:
      name: Self-hosted  # Use Self-hosted Agent Pool

    strategy:
      runOnce:
        deploy:
          steps:
          # Deploy backend to Azure Web App
          - task: AzureWebApp@1
            displayName: 'Deploy Backend to Azure Web App'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux  # App Service type is Linux
              appName: $(webAppName)
              runtimeStack: 'NODE|20-lts'  # Node.js 20 LTS runtime
              package: '$(Pipeline.Workspace)/drop/backend.zip'
              startUpCommand: 'node server.js --port $(serverPort)'  # Command to start the server
