trigger:
  branches:
    include:
      - main  # Kích hoạt pipeline khi có thay đổi trên nhánh 'main'

variables:
  - group: SECRET_KEY
  # Tên Azure Container Registry
  - name: ACR_NAME
    value: wumiibo
  
  - name: FRONTEND_IMAGE
    value: is402-frontend
  - name: BACKEND_IMAGE
    value: is402-backend
  - name: MONGO_IMAGE
    value: mongo
  
  # Azure resources
  - name: APP_NAME
    value: wumiibo    # Azure Web App name
  - name: RESOURCE_GROUP
    value: Wumiibo    # Resource group containing Azure Web App

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images
  pool:
    name: 'Self-hosted 1' # Sử dụng agent Microsoft-hosted
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Images to ACR
    steps:
    - task: AzureCLI@2
      displayName: Login to Azure Container Registry
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299 # Service Connection đến Azure
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):latest -f frontend/Dockerfile .
        docker push $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):latest
      displayName: Build and Push Frontend Image

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE):latest -f backend/Dockerfile .
        docker push $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE):latest
      displayName: Build and Push Backend Image

    - script: |
        docker pull mongo:latest
        docker tag mongo:latest $(ACR_NAME).azurecr.io/$(MONGO_IMAGE):latest
        docker push $(ACR_NAME).azurecr.io/$(MONGO_IMAGE):latest
      displayName: Push MongoDB Image

- stage: Deploy
  displayName: Deploy to Azure Web App
  pool:
    name: 'Self-hosted 1'  # Sử dụng agent Microsoft-hosted
  jobs:
  - job: Deploy
    displayName: Deploy Containers to Azure Web App
    steps:
    - task: AzureCLI@2
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: 974ba5ab-9bc7-41c9-84ac-d53863572299
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config container set `
            --name $(APP_NAME) `
            --resource-group $(RESOURCE_GROUP) `
            --docker-custom-image-name $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE):latest `
            --docker-registry-server-url https://$(ACR_NAME).azurecr.io `
            --docker-registry-server-user $(AZURE_ACR_USERNAME) `
            --docker-registry-server-password $(AZURE_ACR_PASSWORD)
