trigger:
  branches:
    include:
      - main  # Pipeline triggers on changes to the 'main' branch

variables:
  # ACR Configuration
  ACR_NAME: wumiibo3  # Name of the new Azure Container Registry
  RESOURCE_GROUP: Wumiibo  # Current resource group
  LOCATION: southeastasia  # Location of the ACR
  SKU: Basic  # ACR SKU (Basic, Standard, Premium)

  # App Service Configuration
  APP_NAME: wumiibo3  # Name of the App Service
  PLAN_NAME: wumiibo3-Plan  # Name of the App Service Plan
  IMAGE_NAME: your-image-name  # Docker image name
  IMAGE_TAG: latest  # Docker image tag

stages:
- stage: CreateACR
  displayName: Create Azure Container Registry
  jobs:
  - job: CreateACRJob
    displayName: Create ACR Job
    pool:
      name: 'Self-hosted 1'  # Use self-hosted pool
    steps:
    - task: AzureCLI@2
      displayName: Create Azure Container Registry
      inputs:
        azureSubscription: Azure for Students (c4223a0b-6719-4c48-a291-1c557fda900e) # Service Connection name
        scriptType: ps  # Use PowerShell
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "Creating ACR..."
          az acr create `
            --name $(ACR_NAME) `
            --resource-group $(RESOURCE_GROUP) `
            --sku $(SKU) `
            --location $(LOCATION) `
            --admin-enabled true
          Write-Host "ACR created successfully!"

- stage: DeployToAppService
  displayName: Deploy to Azure App Service
  dependsOn: CreateACR  # Ensure ACR is created before deployment
  jobs:
  - job: DeployJob
    displayName: Deploy Application to App Service
    pool:
      name: 'Self-hosted 1'  # Use self-hosted pool
    steps:
    - task: AzureCLI@2
      displayName: Create App Service Plan
      inputs:
        azureSubscription: AzureForStudents-Wumiibo-Connection
        scriptType: ps  # Use PowerShell
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "Creating App Service Plan..."
          az appservice plan create `
            --resource-group $(RESOURCE_GROUP) `
            --name $(PLAN_NAME) `
            --sku B1 `
            --is-linux
          Write-Host "App Service Plan created successfully!"

    - task: AzureCLI@2
      displayName: Deploy Application to App Service
      inputs:
        azureSubscription: AzureForStudents-Wumiibo-Connection
        scriptType: ps  # Use PowerShell
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "Deploying App Service..."
          az webapp create `
            --resource-group $(RESOURCE_GROUP) `
            --plan $(PLAN_NAME) `
            --name $(APP_NAME) `
            --deployment-container-image-name $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)
          Write-Host "App Service deployed successfully!"
