trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the main branch

variables:
  - name: azureSubscription
    value: '974ba5ab-9bc7-41c9-84ac-d53863572299'  # Your Azure subscription ID or service connection name
  - name: ACR_NAME
    value: wumiibo  # Your Azure Container Registry name
  - name: FRONTEND_IMAGE
    value: is402-frontend  # Frontend Docker image name
  - name: BACKEND_IMAGE
    value: is402-backend  # Backend Docker image name

pool:
  name: "Self-hosted 1"  # Use your self-hosted agent pool or change to `Azure Pipelines` for a Microsoft-hosted agent

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images to ACR
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Images
    steps:
    # Log in to Azure CLI
    - task: AzureCLI@2
      displayName: Azure Login
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging in to Azure..."
          az acr login --name $(ACR_NAME)

    # Build and Push Frontend Docker Image
    - task: Docker@2
      displayName: Build and Push Frontend Image
      inputs:
        containerRegistry: $(ACR_NAME).azurecr.io
        repository: $(FRONTEND_IMAGE)
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    # Build and Push Backend Docker Image
    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        containerRegistry: $(ACR_NAME).azurecr.io
        repository: $(BACKEND_IMAGE)
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
