version: '3.7'

services:
  frontend:
    image: wumiibo3.azurecr.io/frontend:latest  # Use prebuilt image in ACR
    container_name: frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - CHOKIDAR_USEPOLLING=true  # Optional if live reload isn't needed in production
    ports:
      - "3000:3000"
    restart: always

  backend:
    image: wumiibo3.azurecr.io/backend:latest  # Use prebuilt image in ACR
    container_name: backend
    env_file: ./backend/.env  # Include environment variables for MongoDB, etc.
    ports:
      - "5000:5000"
    restart: always
