

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app         # Mount the React source code for live reload
      - /app/node_modules       # Preserve node_modules in the container
    ports:
      - "3000:3000"             # Map React development server port
    command: ["npm", "start"]   # Start the React development server
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - CHOKIDAR_USEPOLLING=true  # For reliable hot reloading in Docker


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env  # Load MongoDB Atlas connection string
    ports:
      - "5000:5000"
    networks:
      - is402

networks:
  is402:
    driver: bridge
