version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.UI # Chỉ định đúng tên file
    ports:
      - "3000:80"
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node # Chỉ định đúng tên file
    ports:
      - "5000:5000"
    networks:
      - mern-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:

volumes:
  mongo-data:
