version: '3.8'
services:
  frontend:
    image: wumiibo.azurecr.io/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  # URL kết nối tới backend container
    depends_on:
      - backend

  backend:
    image: wumiibo.azurecr.io/backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/mydatabase  # URL kết nối tới MongoDB container
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=21521226
      - MONGO_INITDB_ROOT_PASSWORD=Nhat22082003
    volumes:
      - /mnt/data/mongo:/data/db
