# Dockerfile

# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install production dependencies only
RUN npm ci --only=production

# Copy application source code
COPY . .

# Set environment to production
ENV NODE_ENV=production

# Expose production port
EXPOSE 5000

# Start server
CMD ["npm", "run", "dev"]
